// Pure logic for generating the sponsor-logo list with per-file CONTENT HASHES in the src
// query (`?v=<hash>`). When a logo's bytes change, its hash changes, the URL changes, and
// browser/edge caches fetch the new image instead of serving the stale one. Kept pure (the
// hash function is injected) so it's unit-testable without touching the filesystem.
export type SponsorLogo = { name: string; src: string };

// Source of truth for the partner roster and the order it reads on the wall.
//
// Deliberately flat. The wall used to be grouped under four category headings, which
// created three problems: it forced a judgement call on every partner (Transit AI landed
// in the wrong bucket), it invited a prospect to notice which box they'd be filed under,
// and a visibly full category implied there was no room left. Category exclusivity is
// still a product we sell; it just isn't announced on the wall.
export const SPONSOR_ROSTER: string[] = [
  'Juniper Apstra', 'Itential', 'Forward Networks', 'Unimus',
  'Transit AI', 'Kentik', 'NetAlly', 'PathSolutions',
  'Augtera', 'Meter', 'Opengear', 'Celona',
  'Netris', 'Cisco Press', 'Boson', 'USNUA',
];

/** Logo display name -> /public/sponsors file basename. */
export const slug = (name: string): string => name.toLowerCase().replace(/\s+/g, '-');

/** Build the logo list with content-hashed srcs. hashFn maps a slug to its short hash. */
export function buildLogos(names: string[], hashFn: (slug: string) => string): SponsorLogo[] {
  return names.map((name) => {
    const s = slug(name);
    return { name, src: `/sponsors/${s}.png?v=${hashFn(s)}` };
  });
}

/** Render the generated TypeScript module string. */
export function renderModule(logos: SponsorLogo[]): string {
  return `// AUTO-GENERATED by scripts/hash-sponsor-logos.ts — do not edit by hand.
// Each src carries an 8-char content hash (?v=) so replacing a logo's bytes changes its URL
// and busts browser/edge cache. Regenerated on every build (see package.json prebuild).
export type SponsorLogo = { name: string; src: string };

export const sponsorLogos: SponsorLogo[] = ${JSON.stringify(logos, null, 2)};
`;
}
