// Pure logic for generating the sponsor-logo list with per-file CONTENT HASHES in the src
// query (`?v=<hash>`). When a logo's bytes change, its hash changes, the URL changes, and
// browser/edge caches fetch the new image instead of serving the stale one. Kept pure (the
// hash function is injected) so it's unit-testable without touching the filesystem.
export type SponsorLogo = { name: string; src: string };
export type SponsorCategory = { category: string; logos: SponsorLogo[] };

// Source of truth for the partner roster + category order. Edit here, then the build
// regenerates components/sponsorLogos.ts with fresh content hashes.
export const SPONSOR_CATEGORIES: { category: string; names: string[] }[] = [
  { category: 'Network Automation', names: ['Juniper Apstra', 'Itential', 'Forward Networks', 'Unimus', 'Transit AI'] },
  { category: 'Observability & Monitoring', names: ['Kentik', 'NetAlly', 'PathSolutions', 'Augtera'] },
  { category: 'Infrastructure & Hardware', names: ['Meter', 'Opengear', 'Celona', 'Netris'] },
  { category: 'Training & Community', names: ['Cisco Press', 'Boson', 'USNUA'] },
];

/** Logo display name -> /public/sponsors file basename. */
export const slug = (name: string): string => name.toLowerCase().replace(/\s+/g, '-');

/** Build the categories with content-hashed srcs. hashFn maps a slug to its short hash. */
export function buildCategories(
  cats: { category: string; names: string[] }[],
  hashFn: (slug: string) => string,
): SponsorCategory[] {
  return cats.map((c) => ({
    category: c.category,
    logos: c.names.map((name) => {
      const s = slug(name);
      return { name, src: `/sponsors/${s}.png?v=${hashFn(s)}` };
    }),
  }));
}

/** Render the generated TypeScript module string. */
export function renderModule(categories: SponsorCategory[]): string {
  return `// AUTO-GENERATED by scripts/hash-sponsor-logos.ts — do not edit by hand.
// Each src carries an 8-char content hash (?v=) so replacing a logo's bytes changes its URL
// and busts browser/edge cache. Regenerated on every build (see package.json prebuild).
export type SponsorLogo = { name: string; src: string };
export type SponsorCategory = { category: string; logos: SponsorLogo[] };

export const sponsorCategories: SponsorCategory[] = ${JSON.stringify(categories, null, 2)};
`;
}
