import { writeFileSync, existsSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { parseFeed } from '../lib/episodes';
import { buildYoutubeMatcher } from '../lib/youtube-match';

const RSS_URL = 'https://rss.buzzsprout.com/2127872.rss';
const OUT_PATH = resolve(process.cwd(), 'data/episodes.json');
const YT_MAP_PATH = resolve(process.cwd(), 'data/youtube_map.json');
const YT_OVERRIDES_PATH = resolve(process.cwd(), 'data/youtube_overrides.json');

async function main() {
  console.log(`Fetching ${RSS_URL}`);
  let xml: string;
  try {
    const res = await fetch(RSS_URL, { headers: { 'User-Agent': 'aone-web build' } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    xml = await res.text();
  } catch (err) {
    console.warn(`Fetch failed (${(err as Error).message}); falling back to existing ${OUT_PATH}`);
    if (!existsSync(OUT_PATH)) {
      throw new Error(`No cached episodes.json to fall back to. Original error: ${(err as Error).message}`);
    }
    return; // keep existing data
  }

  const feed = parseFeed(xml);

  // Enrich with YouTube matches when the channel snapshot is available.
  if (existsSync(YT_MAP_PATH)) {
    const ytMap = JSON.parse(readFileSync(YT_MAP_PATH, 'utf-8'));
    const match = buildYoutubeMatcher(ytMap);
    let matched = 0;
    for (const ep of feed.episodes) {
      const m = match(ep.title);
      if (m) {
        ep.youtube = m;
        matched++;
      }
    }
    console.log(`Matched ${matched}/${feed.episodes.length} episodes to YouTube videos`);
  } else {
    console.warn(`No youtube_map.json at ${YT_MAP_PATH}; skipping YouTube enrichment`);
  }

  // Manual slug → videoId overrides for episodes the fuzzy title matcher can't
  // link (e.g. the YouTube upload was titled differently than the podcast episode).
  if (existsSync(YT_OVERRIDES_PATH)) {
    const overrides = JSON.parse(readFileSync(YT_OVERRIDES_PATH, 'utf-8')) as Record<string, string>;
    let applied = 0;
    for (const ep of feed.episodes) {
      const videoId = overrides[ep.slug];
      if (videoId) {
        ep.youtube = {
          videoId,
          thumbnailUrl: `https://i.ytimg.com/vi/${videoId}/maxresdefault.jpg`,
          watchUrl: `https://www.youtube.com/watch?v=${videoId}`,
        };
        applied++;
      }
    }
    console.log(`Applied ${applied} manual YouTube override(s)`);
  }

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, JSON.stringify(feed, null, 2));
  console.log(`Wrote ${feed.episodes.length} episodes to ${OUT_PATH}`);

  // Also publish it as a static endpoint on the site itself.
  //
  // data/episodes.json is a BUILD ARTIFACT: it is regenerated here on every deploy, so
  // the live site is always current, while the copy committed to git only changes as a
  // side effect of a feature commit (5 times in this repo's life). That was harmless
  // until the AONE mobile app started reading the committed copy from `main`, at which
  // point a file nobody owned went three weeks stale and shipped without the 2026-08-26
  // episode in it.
  //
  // Published here, freshness stops being something anyone maintains: the endpoint is
  // regenerated by the same deploy that publishes the site, so it cannot lag the site.
  // Spec: 2026-09-02-episodes-endpoint-cannot-go-stale-design.md
  const PUBLISHED_PATH = resolve(process.cwd(), 'public/api/episodes.json');
  mkdirSync(dirname(PUBLISHED_PATH), { recursive: true });
  writeFileSync(PUBLISHED_PATH, JSON.stringify(feed, null, 2));
  console.log(`Published ${feed.episodes.length} episodes to ${PUBLISHED_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
